//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FMSWinSvcTester.WebReference {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SAPtoiWMSSoap", Namespace="http://tempuri.org/")]
    public partial class SAPtoiWMS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AAv1903151CHOperationCompleted;
        
        private System.Threading.SendOrPostCallback POInterfaceOperationCompleted;
        
        private System.Threading.SendOrPostCallback DOInterfaceOperationCompleted;
        
        private System.Threading.SendOrPostCallback IMInterfaceOperationCompleted;
        
        private System.Threading.SendOrPostCallback ROInterfaceOperationCompleted;
        
        private System.Threading.SendOrPostCallback RCInterfaceOperationCompleted;
        
        private System.Threading.SendOrPostCallback SKUCreate_TESTOperationCompleted;
        
        private System.Threading.SendOrPostCallback AccountInterfaceOperationCompleted;
        
        private System.Threading.SendOrPostCallback VehicleInterfaceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GIInterfaceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SAPtoiWMS() {
            this.Url = global::FMSWinSvcTester.Properties.Settings.Default.FMSWinSvcTester_WebReference_SAPtoiWMS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AAv1903151CHCompletedEventHandler AAv1903151CHCompleted;
        
        /// <remarks/>
        public event POInterfaceCompletedEventHandler POInterfaceCompleted;
        
        /// <remarks/>
        public event DOInterfaceCompletedEventHandler DOInterfaceCompleted;
        
        /// <remarks/>
        public event IMInterfaceCompletedEventHandler IMInterfaceCompleted;
        
        /// <remarks/>
        public event ROInterfaceCompletedEventHandler ROInterfaceCompleted;
        
        /// <remarks/>
        public event RCInterfaceCompletedEventHandler RCInterfaceCompleted;
        
        /// <remarks/>
        public event SKUCreate_TESTCompletedEventHandler SKUCreate_TESTCompleted;
        
        /// <remarks/>
        public event AccountInterfaceCompletedEventHandler AccountInterfaceCompleted;
        
        /// <remarks/>
        public event VehicleInterfaceCompletedEventHandler VehicleInterfaceCompleted;
        
        /// <remarks/>
        public event GIInterfaceCompletedEventHandler GIInterfaceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AAv1903151CH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AAv1903151CH() {
            this.Invoke("AAv1903151CH", new object[0]);
        }
        
        /// <remarks/>
        public void AAv1903151CHAsync() {
            this.AAv1903151CHAsync(null);
        }
        
        /// <remarks/>
        public void AAv1903151CHAsync(object userState) {
            if ((this.AAv1903151CHOperationCompleted == null)) {
                this.AAv1903151CHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAAv1903151CHOperationCompleted);
            }
            this.InvokeAsync("AAv1903151CH", new object[0], this.AAv1903151CHOperationCompleted, userState);
        }
        
        private void OnAAv1903151CHOperationCompleted(object arg) {
            if ((this.AAv1903151CHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AAv1903151CHCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/POInterface", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string POInterface(string POHead, string POItem, string POItemText, string POSubCon, string userId, string password) {
            object[] results = this.Invoke("POInterface", new object[] {
                        POHead,
                        POItem,
                        POItemText,
                        POSubCon,
                        userId,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void POInterfaceAsync(string POHead, string POItem, string POItemText, string POSubCon, string userId, string password) {
            this.POInterfaceAsync(POHead, POItem, POItemText, POSubCon, userId, password, null);
        }
        
        /// <remarks/>
        public void POInterfaceAsync(string POHead, string POItem, string POItemText, string POSubCon, string userId, string password, object userState) {
            if ((this.POInterfaceOperationCompleted == null)) {
                this.POInterfaceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPOInterfaceOperationCompleted);
            }
            this.InvokeAsync("POInterface", new object[] {
                        POHead,
                        POItem,
                        POItemText,
                        POSubCon,
                        userId,
                        password}, this.POInterfaceOperationCompleted, userState);
        }
        
        private void OnPOInterfaceOperationCompleted(object arg) {
            if ((this.POInterfaceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.POInterfaceCompleted(this, new POInterfaceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DOInterface", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DOInterface(string DOHead, string DOItem, string DOSerialNo, string userId, string password) {
            object[] results = this.Invoke("DOInterface", new object[] {
                        DOHead,
                        DOItem,
                        DOSerialNo,
                        userId,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DOInterfaceAsync(string DOHead, string DOItem, string DOSerialNo, string userId, string password) {
            this.DOInterfaceAsync(DOHead, DOItem, DOSerialNo, userId, password, null);
        }
        
        /// <remarks/>
        public void DOInterfaceAsync(string DOHead, string DOItem, string DOSerialNo, string userId, string password, object userState) {
            if ((this.DOInterfaceOperationCompleted == null)) {
                this.DOInterfaceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDOInterfaceOperationCompleted);
            }
            this.InvokeAsync("DOInterface", new object[] {
                        DOHead,
                        DOItem,
                        DOSerialNo,
                        userId,
                        password}, this.DOInterfaceOperationCompleted, userState);
        }
        
        private void OnDOInterfaceOperationCompleted(object arg) {
            if ((this.DOInterfaceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DOInterfaceCompleted(this, new DOInterfaceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMInterface", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string IMInterface(string IM, string userId, string password) {
            object[] results = this.Invoke("IMInterface", new object[] {
                        IM,
                        userId,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void IMInterfaceAsync(string IM, string userId, string password) {
            this.IMInterfaceAsync(IM, userId, password, null);
        }
        
        /// <remarks/>
        public void IMInterfaceAsync(string IM, string userId, string password, object userState) {
            if ((this.IMInterfaceOperationCompleted == null)) {
                this.IMInterfaceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIMInterfaceOperationCompleted);
            }
            this.InvokeAsync("IMInterface", new object[] {
                        IM,
                        userId,
                        password}, this.IMInterfaceOperationCompleted, userState);
        }
        
        private void OnIMInterfaceOperationCompleted(object arg) {
            if ((this.IMInterfaceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IMInterfaceCompleted(this, new IMInterfaceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ROInterface", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ROInterface(string RO, string userId, string password) {
            object[] results = this.Invoke("ROInterface", new object[] {
                        RO,
                        userId,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ROInterfaceAsync(string RO, string userId, string password) {
            this.ROInterfaceAsync(RO, userId, password, null);
        }
        
        /// <remarks/>
        public void ROInterfaceAsync(string RO, string userId, string password, object userState) {
            if ((this.ROInterfaceOperationCompleted == null)) {
                this.ROInterfaceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnROInterfaceOperationCompleted);
            }
            this.InvokeAsync("ROInterface", new object[] {
                        RO,
                        userId,
                        password}, this.ROInterfaceOperationCompleted, userState);
        }
        
        private void OnROInterfaceOperationCompleted(object arg) {
            if ((this.ROInterfaceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ROInterfaceCompleted(this, new ROInterfaceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RCInterface", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RCInterface(string RCHead, string RCSDetl, string userId, string password) {
            object[] results = this.Invoke("RCInterface", new object[] {
                        RCHead,
                        RCSDetl,
                        userId,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RCInterfaceAsync(string RCHead, string RCSDetl, string userId, string password) {
            this.RCInterfaceAsync(RCHead, RCSDetl, userId, password, null);
        }
        
        /// <remarks/>
        public void RCInterfaceAsync(string RCHead, string RCSDetl, string userId, string password, object userState) {
            if ((this.RCInterfaceOperationCompleted == null)) {
                this.RCInterfaceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRCInterfaceOperationCompleted);
            }
            this.InvokeAsync("RCInterface", new object[] {
                        RCHead,
                        RCSDetl,
                        userId,
                        password}, this.RCInterfaceOperationCompleted, userState);
        }
        
        private void OnRCInterfaceOperationCompleted(object arg) {
            if ((this.RCInterfaceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RCInterfaceCompleted(this, new RCInterfaceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SKUCreate_TEST", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SKUCreate_TEST(string code, string code2, string descr, string userId, string password) {
            object[] results = this.Invoke("SKUCreate_TEST", new object[] {
                        code,
                        code2,
                        descr,
                        userId,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SKUCreate_TESTAsync(string code, string code2, string descr, string userId, string password) {
            this.SKUCreate_TESTAsync(code, code2, descr, userId, password, null);
        }
        
        /// <remarks/>
        public void SKUCreate_TESTAsync(string code, string code2, string descr, string userId, string password, object userState) {
            if ((this.SKUCreate_TESTOperationCompleted == null)) {
                this.SKUCreate_TESTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSKUCreate_TESTOperationCompleted);
            }
            this.InvokeAsync("SKUCreate_TEST", new object[] {
                        code,
                        code2,
                        descr,
                        userId,
                        password}, this.SKUCreate_TESTOperationCompleted, userState);
        }
        
        private void OnSKUCreate_TESTOperationCompleted(object arg) {
            if ((this.SKUCreate_TESTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SKUCreate_TESTCompleted(this, new SKUCreate_TESTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AccountInterface", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AccountInterface(string IM, string userId, string password) {
            object[] results = this.Invoke("AccountInterface", new object[] {
                        IM,
                        userId,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AccountInterfaceAsync(string IM, string userId, string password) {
            this.AccountInterfaceAsync(IM, userId, password, null);
        }
        
        /// <remarks/>
        public void AccountInterfaceAsync(string IM, string userId, string password, object userState) {
            if ((this.AccountInterfaceOperationCompleted == null)) {
                this.AccountInterfaceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccountInterfaceOperationCompleted);
            }
            this.InvokeAsync("AccountInterface", new object[] {
                        IM,
                        userId,
                        password}, this.AccountInterfaceOperationCompleted, userState);
        }
        
        private void OnAccountInterfaceOperationCompleted(object arg) {
            if ((this.AccountInterfaceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AccountInterfaceCompleted(this, new AccountInterfaceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VehicleInterface", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VehicleInterface(string IM, string userId, string password) {
            object[] results = this.Invoke("VehicleInterface", new object[] {
                        IM,
                        userId,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VehicleInterfaceAsync(string IM, string userId, string password) {
            this.VehicleInterfaceAsync(IM, userId, password, null);
        }
        
        /// <remarks/>
        public void VehicleInterfaceAsync(string IM, string userId, string password, object userState) {
            if ((this.VehicleInterfaceOperationCompleted == null)) {
                this.VehicleInterfaceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVehicleInterfaceOperationCompleted);
            }
            this.InvokeAsync("VehicleInterface", new object[] {
                        IM,
                        userId,
                        password}, this.VehicleInterfaceOperationCompleted, userState);
        }
        
        private void OnVehicleInterfaceOperationCompleted(object arg) {
            if ((this.VehicleInterfaceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VehicleInterfaceCompleted(this, new VehicleInterfaceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GIInterface", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GIInterface(string Header, string Items, string userId, string password) {
            object[] results = this.Invoke("GIInterface", new object[] {
                        Header,
                        Items,
                        userId,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GIInterfaceAsync(string Header, string Items, string userId, string password) {
            this.GIInterfaceAsync(Header, Items, userId, password, null);
        }
        
        /// <remarks/>
        public void GIInterfaceAsync(string Header, string Items, string userId, string password, object userState) {
            if ((this.GIInterfaceOperationCompleted == null)) {
                this.GIInterfaceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGIInterfaceOperationCompleted);
            }
            this.InvokeAsync("GIInterface", new object[] {
                        Header,
                        Items,
                        userId,
                        password}, this.GIInterfaceOperationCompleted, userState);
        }
        
        private void OnGIInterfaceOperationCompleted(object arg) {
            if ((this.GIInterfaceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GIInterfaceCompleted(this, new GIInterfaceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void AAv1903151CHCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void POInterfaceCompletedEventHandler(object sender, POInterfaceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class POInterfaceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal POInterfaceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void DOInterfaceCompletedEventHandler(object sender, DOInterfaceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DOInterfaceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DOInterfaceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void IMInterfaceCompletedEventHandler(object sender, IMInterfaceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IMInterfaceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IMInterfaceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ROInterfaceCompletedEventHandler(object sender, ROInterfaceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ROInterfaceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ROInterfaceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void RCInterfaceCompletedEventHandler(object sender, RCInterfaceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RCInterfaceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RCInterfaceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void SKUCreate_TESTCompletedEventHandler(object sender, SKUCreate_TESTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SKUCreate_TESTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SKUCreate_TESTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void AccountInterfaceCompletedEventHandler(object sender, AccountInterfaceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccountInterfaceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AccountInterfaceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void VehicleInterfaceCompletedEventHandler(object sender, VehicleInterfaceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VehicleInterfaceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VehicleInterfaceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GIInterfaceCompletedEventHandler(object sender, GIInterfaceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GIInterfaceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GIInterfaceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591